//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeetCode.Tests {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeetCode.Tests.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 bwvzoubsovtdpokbjgubpkzsdmxpdxwrkjzjbhcuvppjowoaapfpaqmgpkflwookqdujdfqsifdbkmwqfumwhotpdmevmshumjcdquspnihgceaedgxjgrtjdxqacznaluiiwrivaulamzyecdpyfyxmiavwkqvbybabmshszoslhxzhmaqtvhbnznnxuyctrbywifcuguutkdxchpyxurmskwbygnbtatoxwesmtzchjlrnqsjxanoemmzsqcraykiszrieoaqcwcwlyorrcvlamxztujsglqcwjmqvcmmuwwjgkdfhfxfahlefserldejymbhgdddlwjllantqxeivdbrsbjdcsgrcngejbfvwdjbaffvarzdkizozlszqvzsyszqklvinaypeqyppcyafzqkdlreddrmbxwiikymgcqaghptuvbgkoebirotkfdxcfxeykqvdqlbmnbpgumksbsdwdbyqfdwdqpfustxqorwpxyatjuiocqjytiqz [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string P1044Input2 {
            get {
                return ResourceManager.GetString("P1044Input2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 baaddcedaabeeebbddcdcdbaedcadbcbedddbbcbcbcdddbdddbdebecedabbdccdabbaaeedcbcacbcdebebaeeecaaddeceabbcaddabeceaceebedcabbcdcdbabdeeeacaceabaaaaeaeabbdecbdebedcedacbecccaeacbadecedbacbcdcebddebabbdddcdbbdccbdaccacaccbaabebcdbeadbdeebddbdddbabbeaeeabbdbcbcaaccdcabaebeadcaddeedcabebcbdbbbcdeeabbbadcbbadddadaddeacdbbbbecdadababacabcceaccdaddbcbbbccbdddacadcddddedeaeabebcdcaccceeecbdcaeebeabedbececeadbdcdcedadbbebedaaeacbedecddcabeddbadaaeceedbbedaadcbdebcbbbdcbeccaadeacdbebaedadadddbebccacecbcecdeeadaebbdbaeeaee [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string P1044LongTestData {
            get {
                return ResourceManager.GetString("P1044LongTestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1360,8482,-7592,-4098,4765,4238,1210,-7849,477,-7437,-9823,-4930,-9000,9739,5582,6902,-9675,6526,8062,7751,-2544,2112,9941,8684,9290,-9504,-6446,-7024,323,6415,1473,-8209,-7881,-1667,-5858,-1310,9624,-3689,-2261,-8158,-3213,-790,9545,-9003,-118,-6931,-5869,8338,3638,-9083,-6635,4779,2331,7781,-2149,-4560,993,2201,-9537,-446,-6594,-8501,967,9001,-4033,-3804,8858,5530,-1276,7612,-8602,-6879,-6291,2227,-2486,-1015,-2927,6760,2459,-8057,-2699,6387,5144,8002,-2357,-2235,8724,-5338,695,-4070,2963,356,-9047,-4159, [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string P1191Input1 {
            get {
                return ResourceManager.GetString("P1191Input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2566,5469,1898,127,2441,4612,2554,5269,2785,5093,3931,2532,1195,1101,1334,2124,1156,3400,747,5046,3325,4039,1858,3655,4904,2255,1822,972,5175,2880,2776,4900,2172,3808,3441,4153,3969,3116,1913,5129,4839,4586,752,1804,1970,4052,5016,3781,5000,4331,2762,4886,826,1888,1175,2729,1610,1634,2773,543,2617,4990,3225,2962,4963,3575,3742,3424,3246,5067,133,2713,2667,4043,663,3442,1714,386,3864,1978,1363,27,630,4652,1537,1770,893,2676,2608,3842,4852,5248,832,1689,1033,3849,1471,3373,2764,2453,5272,1313,1005,5083,2191,4 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string P493Input1 {
            get {
                return ResourceManager.GetString("P493Input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -32663,-36605,66224,14387,51418,30434,18347,98126,-8323,-33339,36769,79109,-23194,-9896,67990,-11414,-4629,21792,46755,84877,69128,-49061,79216,28735,42774,92620,49628,77186,86172,87886,77863,90207,-8642,52710,-2221,-19651,68274,85289,50032,-20487,-21518,5867,76156,79318,58624,74509,47490,96533,63340,-26205,62570,43318,62258,65898,72308,-4536,85462,-22971,84011,40816,98631,73874,-44803,-1863,79146,64637,-31262,-37111,26479,15333,-6392,-42227,-4596,71074,98010,10609,88515,-36203,-6087,44768,25376,-11025,-328 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string P862LongTestData {
            get {
                return ResourceManager.GetString("P862LongTestData", resourceCulture);
            }
        }
    }
}
